name: Docker Compose CI/CD

on:
  push:
    branches:
      - master  
  pull_request:
    branches:
      - master 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Clean up Docker space
      run: |
        docker system prune -af --volumes

    - name: Set up Docker
      uses: docker/setup-buildx-action@v2

    - name: Build containers
      run: |
        docker compose -f docker-compose.yml build
