name: Docker Compose CI/CD

on:
  push:
    branches:
      - master  
  pull_request:
    branches:
      - master 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Set up Docker
    - name: Set up Docker
      uses: docker/setup-buildx-action@v2

    # Step 3: Build and tag Docker containers using Docker Compose
    - name: Build containers
      run: |
        docker compose -f docker-compose.yml build
